config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/disclaimer', to: 'static_pages#disclaimer'
  get '/emissions_form', to: 'emissions_form#index'

  namespace :emissions do
    resources :dashboard
    resources :power_emissions
  end

  namespace :api do
    namespace :v1 do
      post 'contact', to: 'contact#send_email'
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def disclaimer
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<%= react_component("Contact") %>

app/views/static_pages/disclaimer.html.erb
<% provide(:title, "Disclaimer") %>
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-two-thirds">
        <div class="content"><%= render 'disclaimer_text' %></div>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-two-thirds">
        <div class="content"><%= render 'home_text' %></div>
      </div>
    </div>
  </div>
</section>
<section>
  <div class="container has-text-centered page__last-element">
    <%= link_to "Start here", emissions_form_path,
      class: "button is-link is-rounded" %>
  </div>
</section>