config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/disclaimer', to: 'static_pages#disclaimer'
  get '/emissions_form', to: 'emissions_form#index'

  namespace :emissions do
    resources :dashboard
    resources :power_emissions
  end

  namespace :api do
    namespace :v1 do
      post 'contact', to: 'contact#send_email'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/automotive_fuel_price.rb
class AutomotiveFuelPrice < ApplicationRecord
  FUEL_NAMES = %w[diesel reg_petrol prem_petrol].freeze

  validates :month_beginning,
            presence: true

  validates :fuel_type,
            presence: true,
            inclusion: { in: FUEL_NAMES, message: '%{value} is not a valid fuel name' }

  validates :fuel_price,
            numericality: { greater_than_or_equal_to: 0.0, less_than_or_equal_to: 300.0 },
            allow_nil: false
end

app/models/coal_emission_adjustment.rb
class CoalEmissionAdjustment < ApplicationRecord
  validates :month,
            presence: true,
            numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 12 }
  validates :adjust_factor,
            presence: true,
            numericality: { greater_than_or_equal_to: 0.0, less_than_or_equal_to: 1.0 }
end

app/models/emission_factor.rb
class EmissionFactor < ApplicationRecord
  FUEL_NAMES = %w[diesel reg_petrol prem_petrol natural_gas coal].freeze
  UNIT_NAMES = %w[kgCO2/litre kgCO2/kWh tCO2/TJ]

  validates :fuel_type,
            presence: true,
            inclusion: { in: FUEL_NAMES, message: '%{value} is not a valid fuel name' }

  validates :units,
            presence: true,
            inclusion: { in: UNIT_NAMES, message: '%{value} is not a valid unit name' }

  validates :factor,
            presence: true,
            numericality: true
end

app/models/energy_type.rb
class EnergyType < ApplicationRecord
  validates :name,
            presence: true,
            uniqueness: true
end

app/models/generation_station.rb
class GenerationStation < ApplicationRecord
  FUEL_NAMES = %w[geothermal coal natural_gas diesel hydro wood_waste wind process_waste].freeze

  validates :station_name, presence: true
  validates :poc,
            presence: true,
            format: { with: /[A-Z]{3}\d{4}\s[A-Z]{3}\d{1,2}\z/, message: 'must be a valid point of connection' }
  validates :generation_type, presence: true
  validates :fuel_name,
            presence: true,
            inclusion: { in: FUEL_NAMES, message: '%{value} is not a valid fuel name' }
  validates :generation_type, presence: true
  validates :primary_efficiency, presence: true, numericality: true
  validates :emissions_factor,
            numericality: { greater_than_or_equal_to: 0.0, less_than_or_equal_to: 1.1 },
            allow_nil: true
end

app/models/half_hourly_emission.rb
class HalfHourlyEmission < ApplicationRecord
  include HalfHourlyEmissionValidation
end

app/models/period_types.rb
module PeriodTypes
  def self.list
    periods = (1..50).map { |n| n.to_s } << %w[ wkday wkend ]
    periods.flatten
  end
end

app/models/processed_emi_file.rb
class ProcessedEmiFile < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
  include PeriodTypes

  validates :period,
            presence: true,
            inclusion: { in: PeriodTypes.list << 'month' }
  validates :month,
            presence: true,
            numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 12 }
  validates :profile,
            presence: true,
            numericality: { greater_than_or_equal_to: 0.0, less_than_or_equal_to: 1.0 }
  validates :energy_type,
            presence: true,
            numericality: { only_integer: true },
            inclusion: { in: EnergyType.pluck(:id) }
end

app/models/temp_half_hourly_emission.rb
class TempHalfHourlyEmission < ApplicationRecord
  include HalfHourlyEmissionValidation
end

app/models/trader.rb
class Trader < ApplicationRecord
  validates :code,
            presence: true,
            format: { with: /[A-Z]{4}/, message: 'must be a valid point of trader' }
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # To perform put, patch, delete requests from API, we need to add following code to
  protect_from_forgery with: :null_session
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def disclaimer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Available for all views
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = 'Carbon Foot Prints'
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def previous_month
    Date.parse(Time.new.to_s).prev_month
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def bar_data(query_data, label_title, data_title)
    { labels: query_data.reduce([]) {|labels, data_pt| labels << data_pt[label_title].to_s},
      datasets: [
        { label: "User Emissions",
          barPercentage: 0.5,
          barThickness: 6,
          maxBarThickness: 8,
          minBarLength: 2,
          data: query_data.reduce([]) {|data, data_pt| data << data_pt[data_title].to_s},
          backgroundColor: [ 'hsl(37, 90%, 51%)', 'hsl(204, 70%, 81%)']
        }] }
  end

  def bar_options
    {
      height: 200,
      legend: {display: false},
      scales: {
        yAxes: [{ scaleLabel: { display: true,
                                labelString: 'Emisssions Source' },
                  gridLines: { offsetGridLines: true }
                }],
        xAxes: [{ scaleLabel: { display: true,
                                labelString: 'Emisssions kgCO2' }
                }],
      }
    }
  end
end

app/helpers/emissions_form_helper.rb
module EmissionsFormHelper
end

app/helpers/emissions_helper.rb
module EmissionsHelper
  # Refactoring required

  def chart_data(query_data, label, data_name, background_color)

    labels = []
    data = []
    query_data.each do |data_item|
      labels << data_item[label].to_s

      data << data_item[data_name]
    end

    pp labels
    pp data
    # "rgba(220,220,220,0.2)"

    { labels: labels,
      datasets: [
        { label: "My First dataset",
          backgroundColor: background_color,
          borderColor: "rgba(220,220,220,1)",
          data: data
        }] }
  end

  def user_emissions_options
    {
      scales:
        { yAxes: [{ scaleLabel: { display: true,
                    labelString: 'Emisssions kgCO2' }
                  }],
          xAxes: [{ scaleLabel: { display: true,
                    labelString: 'Time hours: minutes' }
                  }]
        }
    }
  end

end

app/helpers/power_emissions_helper.rb
module PowerEmissionsHelper

  def line_data(query_data, label_title, data_title)

    { labels: query_data.reduce([]) {|labels, data_pt| labels << data_pt[label_title].to_s},
      datasets: [
        { label: "User Emissions",
          fill: false,
          borderColor: "rgba(43,101,247,1)",
          borderJoinStyle: "round",
          pointStyle: "line",
          data: query_data.reduce([]) {|data, data_pt| data << data_pt[data_title].to_s}
        }] }
  end

  def line_options
    {
      height: 270,
      legend: {display: false},
      scales:
        { yAxes: [{ scaleLabel: { display: true,
                    labelString: 'Emisssions kgCO2' }
                  }],
          xAxes: [{ scaleLabel: { display: true,
                    labelString: 'Time hours: minutes' },
                    gridLines: {display: false }
                  }]
        }
    }
  end

  def doughnut_data(query_data, label_title, data_title)

    { labels: query_data.reduce([]) {|labels, data_pt| labels << data_pt[label_title].to_s},
    datasets: [
      { label: "My First dataset",
        backgroundColor: ['red', 'green', 'blue', 'pink', 'purple', 'yellow'],
        data: query_data.reduce([]) {|data, data_pt| data << data_pt[data_title].to_s}
      }] }
  end

  def doughnut_options
  {
    height: 270,
    legend: {
      position: 'bottom'
   }
  }
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class='footer'>
  <div class='container'>
    <div class='level'>
      <div class='level-left'>
        <div class='level-item footer--logo has-text-centered-mobile'>
          <h1 class='title is-6 has-text-white is-family-secondary'> Green Foot Prints </h1>
        </div>
      </div>
      <div class='level-right is-size-7 has-text-weight-semibold'>
        <p class='level-item'>
          <%= link_to 'About', about_path, class: 'has-text-grey-darker footer--menu' %>
        </p>
        <p class='level-item'>
          <%= link_to 'Contact Us', contact_path, class: 'has-text-grey-darker footer--menu' %>
        </p>
        <p class='level-item'>
          <%= link_to 'Disclaimer and copy right', disclaimer_path, class: 'has-text-grey-darker footer--menu' %>
        </p>
      </div>
    </div>
    <div class='level footer--copyright'>
      <div class='level-left'>
        <div class='level-item'>
        </div>
      </div>
      <div class='level-right is-size-7'>
        <div class='level-item'>
          <span class='icon is-small'>
            <%= fa_icon 'copyright' %>
          </span>
          <p class='content'>
            2018 Steve Torrens
          </p>
        </div>
      </div>
    </div>
  <div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar is-fixed-top">
  <div class="container">

    <div class="navbar-brand">
      <div class="navbar-item navbar--logo">
        <h1 class="title is-5 has-text-white is-family-secondary"> Green Foot Prints </h1>
      </div>
      <%= link_to "Home", root_path, class: "navbar-item navbar--menu is-size-4" %>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="has-navbar-fixed-top">
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>